# Generated by Django 3.0.5 on 2021-09-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210921_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='current_time',
            new_name='input_values',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='current_user',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='desending_order',
            new_name='user_id',
        ),
    ]
